-- ---------------------------------------------------------
-- Real-World Data Analysis Cases (Mode)
-- ---------------------------------------------------------
-- The following section aims to replicate real problems of 
-- analysis, beyond SQL synthax, to understand the 
-- application of what we are measuring with this tool.
--
-- This section will start with Yammer, a social network to
-- communicate with coworkers, share docs, or ideas by posts
-- within groups. Yammer has a centralized Analytics team, 
-- which sits in the Engineering organization and whose goal 
-- is to drive better product and business decisions using 
-- data. 
--
-- They do this partially by providing tools and education 
-- that make other teams within Yammer more effective at 
-- using data to make better decisions. They also perform 
-- ad-hoc analysis to support specific decisions.
--
-- Yammer analysts are trained to constantly consider the 
-- value of each individual project; they seek to maximize 
-- the return on their time. Analysts typically opt for less 
-- precise solutions to problems if it means investing 
-- substantially less time as well.
--
-- They are also taught to consider the impact of everything 
-- on the company at large. This includes high-level decision 
-- making like choosing which projects to prioritize. It also 
-- influences the way analysts think about metrics. Product 
-- decisions are always evaluated against core engagement, 
-- retention, and growth metrics in addition to product-
-- specific usage metrics (like, for example, the number of 
-- times someone views another user's profile).

-- ---------------------------------------------------------
-- The Cases
-- ---------------------------------------------------------
--
-- A Drop in Engagement
-- Engagement dips—you figure out the source of the problem.
--
-- Understanding Search
-- The product team is thinking about revamping search. Your 
-- job is to figure out whether they should change it at all, 
-- and if so, what should be changed.
--
-- The Best A/B Test Ever
-- A new feature tests off the charts. Your job is to 
-- determine the validity of the experiment.

-- ---------------------------------------------------------
-- All of those cases will be developed in the following
-- files tagged "SQL Analystics", on a case-per-case basis.